name: Verify Unit tests

on:
  pull_request:
    paths:
      - 'support/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: v1.19
        import-path: github.com/project-codeflare/codeflare-common

    - name: Run unit tests
      run: go test ./support/. -v
    